# docker-compose.yml
services:
  postgres:
    image: postgres:16-alpine
    container_name: drone_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dat1110
      POSTGRES_PASSWORD: tuandat1110
      POSTGRES_DB: drone_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: